// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opgasirtlbquxyyrgjud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZ2FzaXJ0bGJxdXh5eXJnanVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTk0NDcsImV4cCI6MjA2NjA5NTQ0N30.lK1AAk94aWwcMHdUwoLiP24yxYG21Z3vxrMuHXfVl6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);